# DEIM/configs/byu_deim_2d_slice_config.yml
__include__: [
  './dataset/byu_slice_detection.yml',    # 위에서 만든 데이터셋 설정
  './runtime.yml',                         # DEIM 기본 런타임 설정
  # DEIM의 2D 증강 및 학습 전략을 가져옴
  './base/optimizer.yml',               # DEIM 기본 옵티마이저/스케줄러
  # 사용할 2D 모델 아키텍처 (예: RT-DETRv2-R50 기반)
  './base/dfine_hgnetv2.yml',             # DFINE + HGNetv2 아키텍처 기본값
  './base/deim.yml',              # Mosaic, Mixup 등 DEIM 학습 전략
]

output_dir: ./outputs/byu_deim_2d_slice_exp001 # 결과 저장 경로


# HGNetv2의 세부 설정 (예: name: 'B0', 'B2', 'B4', 'B5') 오버라이드 가능
HGNetv2:
  name: 'B5' # 예시: 모델 크기 선택
  # pretrained: True # dfine_hgnetv2.yml에 이미 있을 것임
  # local_model_dir: 경로/to/pretrained_hgnetv2_weights

# --- 모델 및 학습 파라미터 오버라이드 (필요시) ---
# num_classes는 byu_slice_detection.yml에서 이미 1로 설정됨 (모터 단일 클래스)
# DEIMCriterion의 num_classes도 이에 맞게 설정됨 (rt_deim.yml에서 num_classes 전역 변수 참조)

# 입력 이미지 크기 (각 슬라이스는 512x512)
eval_spatial_size: [512, 512] # H, W - 2D 모델이므로
val_freq: 5  # 10에폭마다 검증
flat_epoch: 19     # 계산: 4(warmup_epoch 가정) + (30(epoches) - 4) / 2 = 17. rt_deim.yml은 4 + epoch//2 = 4 + 30//2 = 19. 현재 값 유지.
no_aug_epoch: 2     # 학습 마지막에 증강 없이 학습할 에폭 수. 너무 짧으면 효과 미미. (예: epoches의 10% = 3 에폭)
warmup_iter: 1000
# 학습 에폭, 배치 크기 등은 rt_optimizer.yml 또는 여기서 조정 가능
epoches: 30 # 예시
train_dataloader:
  batch_size: 64 # GPU 메모리에 맞게 조절 (슬라이스 단위이므로 배치 늘리기 용이)
  # transforms ops는 rt_deim.yml 것을 사용. 필요시 여기서 오버라이드.
  # 예: Resize 크기를 512x512로 명시하거나, Normalize 파라미터 변경
  dataset:
    transforms:
      ops:
        # 1) Mosaic (확률 낮춤)
        - {type: Mosaic, output_size: 512, probability: 0.5, fill_value: 114}

        # 2) PhotometricDistort (색/명암 변환)
        - {type: RandomPhotometricDistort, p: 0.5}
        
        # # # 3) ZoomOut
        # - {type: RandomZoomOut, fill: 114, p: 0.5}
        
        # # # 4) IoUCrop
        # - {type: RandomIoUCrop, p: 0.8}
        
        # 5) HorizontalFlip
        - {type: RandomHorizontalFlip, p: 0.5}

        # 6) Resize
        - {type: Resize, size: [512, 512]}
        
        # 7) SanitizeBoundingBoxes (최종 한 번)
        - {type: SanitizeBoundingBoxes, min_size: 1}
        
        # 8) ConvertBoxes + Normalize
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}

      policy: # 증강 적용/중단 시점 (rt_deim.yml의 값을 현재 epoches에 맞게 조정)
        name: stop_epoch # rt_deim.yml의 policy.name을 명시적으로 가져옴
      #   epoch: []
      #   ops : []
      # mosaic_prob: -0.1
        epoch: [4, 19, 28] # [4, 14, 18]
                           # 계산: [warmup 종료 시점 근처, flat_epoch, epoches - no_aug_epoch]
                           # rt_deim.yml의 epoch: [4, 29, 50]은 epoches=58 기준이었음.
                           # 이 값을 현재 설정된 epoches, flat_epoch, no_aug_epoch에 맞게 재계산 필요.
        ops: ['Mosaic', 'RandomPhotometricDistort'] # rt_deim.yml의 policy.ops
      mosaic_prob: 0.2 # rt_deim.yml 값 사용 또는 여기서 오버라이드
  # collate_fn:
  #   mixup_prob: 0.0  # mixup 끔
  #   mixup_epochs: [4, 11]
  #   stop_epoch: 999  # 어차피 mixup_prob=0이면 안 쓰임

  collate_fn: # rt_deim.yml 설정을 기반으로 하되, BYU 데이터에 맞게 조정
    # type: BatchImageCollateFunction 은 rt_deim.yml 에서 상속됨
    base_size: 512 # 입력 슬라이스 크기와 일치
                   # 이유: 멀티스케일 학습 시 기준 크기. 단일 스케일이면 이 값으로 고정.
    # base_size_repeat: 3 # rt_deim.yml 값. 멀티스케일 학습 시 다양성 증가.
    # scales: null # 단일 스케일(512) 학습 시 명시적으로 null 또는 [[512,512]]로 설정하여 멀티스케일 비활성화.
                   # 또는 stop_epoch: 0 으로 설정.
                   # 로그에 "Multi-scales@ None" 이므로 현재 scales가 None인 상태로 보임.
                   # 만약 단일 스케일로 학습하고 싶다면 이 상태 유지.
    mixup_prob: 0.1 # MixUp 확률 (기본 0.5에서 줄여봄. BYU 데이터 특성상 과도한 Mixup이 불리할 수 있음)
                    # 이유: 실험적으로 조절.
    mixup_epochs: [4, 19] #  [4, 14] MixUp 적용 에폭 (위 policy.epoch[0], policy.epoch[1]과 유사하게 설정)
                          # 이유: 학습 초중반에만 적용.
    stop_epoch: 28    # 멀티스케일 학습 및 특정 증강 중단 에폭 (policy.epoch[2]와 일치)
                      # 이유: 학습 후반에는 안정적인 학습을 위해 강한 증강 중단.

val_dataloader:
  batch_size: 64
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [512, 512]}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}





